---
apiVersion: v1
kind: Service
metadata:
  name: sshanmugam-clamav-svc
  labels:
    app: sshanmugam-clamav
spec:
  type: NodePort
  ports:
    - name: clamav-port
      targetPort: 9000
      nodePort: 30080
      port: 30080
  selector:
        app: sshanmugam-clamav
